### ISSUE TITLE
Using --textafter

### ISSUE THREAD

**Issue by Tomas-M** [Tomas-M/xlunch#50] opened 2017-10-29 18:58 UTC
When using --textafter, there is a mouse cursor position between items which highlights two items at the same time. I assume this is a bug which should be fixed.

**Comment by PMunch** [comment] 2017-10-29 20:51
Using what command on which screen resolution? When I just use `--textafter 20` it displays fine, but if I force up the amount of rows with `--textafter 20 --rows 10` I get some overlap between items since it doesn't actually have space for 10 rows within the borders. Either using the default or manually setting it to something <10 makes it work fine again.

A screenshot would be helpful as well. Here I've attached some displaying what I think you're seeing:
![noverlap](https://user-images.githubusercontent.com/2845482/32148243-3df24842-bcf4-11e7-9b42-e03388c4f246.png)
This is with no overlap, the mouse cursor is placed in the bottom of the selected application. `xlunch --textafter 20 --columns 2 --rows 9`

![overlap](https://user-images.githubusercontent.com/2845482/32148244-3e0f12f6-bcf4-11e7-84ee-ddae0ac1ba33.png)
Here we can see the rows overlapping, caused by too many rows. `xlunch --textafter 20 --columns 2 --rows 10`

**Comment by Tomas-M** [comment] 2017-10-29 21:10
-n --desktop --dontquit -b 40 --textafter 20
screen resolution 1024x768
three icons (from make test)
You must position the cursor right between the items, there is only one pixel boundary where this happens...

![screen](https://user-images.githubusercontent.com/2259370/32148346-e49ab868-bcf5-11e7-9f30-0966f481d818.png)

**Comment by PMunch** [comment] 2017-10-29 23:04
Ah, since you only have those three icons it's probably something in the calculation of sizes. It probably rounds down or up were it shouldn't making a 1px overlap. I'll fix it tomorrow, shouldn't be too hard.

**Comment by Tomas-M** [comment] 2017-10-30 09:16
Maybe this is related to the margin calculation as well?

**Comment by Tomas-M** [comment] 2017-10-30 09:18
It seems to me the textafter got broken after the last changes.

**Comment by PMunch** [comment] 2017-10-30 09:26
Ah, I had replaced one too many variable. Fixed it now.

**Comment by PMunch** [comment] 2017-11-01 09:48
Fixed in https://github.com/Tomas-M/xlunch/commit/7f928d1e259b69beace40bc297f6b734a3fe2cae. This is actually something that has been a bug all along, it's just the new system of showing as many icons as possible that makes it apparent. You should be able to provoke it in earlier version by setting margin to 0 or similar.

**Closed as completed** 2017-11-01 09:48 UTC
Labels: bug
