### ISSUE TITLE
No icons with autostart in openbox

### ISSUE THREAD

**Issue by keiem** [Tomas-M/xlunch#105] opened 2019-02-11 09:36 UTC
When I autostart xlunch in openbox, I don't have icons on the desktop although xlunch is running.  When I do a killall xlunch and start it again with xlunch -dnq then everything works as expected.

It's acustom install on manjaro linux.  I have also compton and tint2 started in my autostart configuration.

**Comment by PMunch** [comment] 2019-02-22 09:33
Hmm, could you try writing xlunch messages to a log file so we can see what happens? Something like `xlunch 2>/tmp/xlunch.log`.

**Comment by keiem** [comment] 2019-03-04 14:16
I tried this but the log is empty.

**Comment by PMunch** [comment] 2019-03-05 08:03
Hmm, that should mean it doesn't have anything to complain about. Can you confirm that `xlunch` is running on your machine, or did it stop? Do you see the background image/colour you set, or just your regular background image? It might be some race condition where it is faster to start than something it depends on, or something that draws over it.

**Comment by keiem** [comment] 2019-03-05 08:11
Xlunch is running as I can kill it.  I also see the background from xlunch,
but no icons.  My first idea was it loads to quick, so I added a sleep time
off 4 seconds (maybe to short).  2nd thought was it was conky so I removed
it from the autostart as it doesn't fit together with xlunch.  My last idea
is tint2.  I have it also started in my autostart file but I didn't change
anything yet cause I'm on little time lately.  Point is when I start xlunch
manually after tint2 is already running, it works.  So tint2 and xlunch can
run on the same time.  Myabe I should remove xlunch out of my autstart and
make a user systemd instance for it.

Op di 5 mrt. 2019 om 09:03 schreef PMunch <notifications@github.com>:

**Comment by PMunch** [comment] 2019-03-05 08:55
Ah now that I think about it this might be related to another issue. See [this](https://github.com/Tomas-M/xlunch/issues/91#issuecomment-412089291) comment, I think it's the same issue.

**Comment by fredx181** [comment] 2019-03-12 07:07
> Ah now that I think about it this might be related to another issue. See [this](https://github.com/Tomas-M/xlunch/issues/91#issuecomment-412089291) comment, I think it's the same issue.

Yes, that's probably it, for me also no icons show when running xlunch from openbox autostart.
Fix is to specify input e.g. `-i /path/to/entries.dsv` 
Or use something like:
```
[ -f $HOME/.config/xlunch/entries.dsv ] && ENTRIES=$HOME/.config/xlunch/entries.dsv || ENTRIES=/etc/xlunch/entries.dsv
xlunch -i $ENTRIES .... ..... ....
```

**Comment by PMunch** [comment] 2019-03-20 07:21
Closing this as a duplicate of #91

**Closed as completed by PMunch** 2019-03-20 07:21 UTC
