### ISSUE TITLE
Hitting enter to run first item only works when there is one item in the list.

### ISSUE THREAD

**Issue by ghost** [Tomas-M/xlunch#42] opened 2017-09-08 21:04 UTC
If I have 1+ items in in the search list nothing happens when I hit enter. I feel this would only make sense if I hadn't searched for anything at all. But also being able to hit enter right away could also be practical for example if the first item in the list is a web browser, terminal, or other often used software.

**Comment by PMunch** [comment] 2017-09-08 22:39
The idea is that you should also be able to freely type commands into the run field. There is a switch `--selectonly` which makes it so that you can only select entries that are actually in the list and not freely typed ones, and I've planned to make it so when this mode is enabled you will select the first entry even if multiple entries are shown.

**Comment by ghost** [comment] 2017-09-09 09:29
Well, what I had in mind was how dmenu_run does it where you are always able to run the first item in the list (without pressing tab or right arrow), but when you type something that isn't in the list it just runs that as a command. I don't think it's needed to have a selectonly mode to solve the problem, but a selectonly mode will surely still be useful for someone. What I'm getting at here is just that it would be nice to not have to either press tab or right arrow because why have extra steps, it's a launcher it's supposed to be quick.

**Comment by Tomas-M** [comment] 2017-09-09 09:45
@AndersBH Please submit a patch and I will accept it.

**Comment by Tomas-M** [comment] 2017-09-09 09:47
Ideally, add --erunfirst so that pressing Enter runs first icon if there are icons, or runs the commandline as command if there are no icons.

**Comment by PMunch** [comment] 2017-09-10 19:22
@AndersBH the problem then is if you want to run a command that happens to collide with the name of a program. That's why I was planning on making `--selectonly` ignore running commands and rather always selecting the first option.

**Comment by PMunch** [comment] 2017-09-10 19:23
Sorry, didn't mean to close the issue, my mouse slipped..

**Comment by ghost** [comment] 2017-09-10 21:00
@PMunch okay, sounds great. Maybe add a `Ctrl+Enter` or `Shift+Enter` feature to `--selectonly` to run current input as a command. BTW: I'm not a C programmer, so if you like it, add it if you like. I will at least try to add it to my own installation if nothing else.

**Comment by PMunch** [comment] 2017-09-11 10:53
Well, the point with `--selectonly` is to enforce only selections. It's mostly as a convenience to people who wants to write scripts that interacts with xlunch so that you are sure that you can't get anything but what you passed in as output.

**Comment by PMunch** [comment] 2017-11-01 10:02
`--selectonly` now runs the first application in the list when enter is pressed as of https://github.com/Tomas-M/xlunch/commit/734f44f2e9e3d739536ed3f934e83f8665f5cf6b

**Comment by Tomas-M** [comment] 2017-11-28 14:13
I am a bit confused by the behavior, and I am not sure how to solve it - when user hovers a mouse cursor over some icon, and then user hits Enter, the first application is started regardless of the hovered position. I am not sure if this is correct. I am thinking, maybe we could run the hovered app? And run the first one only if nothing was hovered yet? I'm unsure what is better. For me, it would be probably more intuitive to run the hovered app.

Maybe this does not apply only to --selectonly, but in general.

**Comment by PMunch** [comment] 2017-11-28 15:29
Yeah, this is the same behaviour as xlunch has always had I think. I just assumed you wanted it that way and didn't change it. I can easily change that behaviour. There is one case though, when the user is not really using the mouse but interacting with a terminal program. When running xlunch an arbitrary icon under the cursor would be highlighted, and the user would need to manually select the first item if that is the one that is wanted. This is quite the edge case though as all highlights get removed when typing anything.

**Comment by Tomas-M** [comment] 2017-11-28 16:32
I can see.
My problem is that I see a highlighed item and pressing Enter runs different item.
Or I do not see any item highlighted and pressing Enter runs the first.

It is a puzzle, because:
If I start xlunch with mouse, I expect the item under cursor to be highlighted.
If I start xlunch with keyboard (eg. shortcut or running command), I expect the item under cursor not highlighed.
But xlunch cannot know how the user started it.

So, I would suggest the following three:
1) highlight item under cursor on start only if some commandline parameter is present, like --highlightundermouseonstart :=)
2) make Enter key always run icon under cursor. If none is highlighed, run command typed. If there is no command typed, Enter does nothing (do not quit xlunch)
3) Furthermore if --selectonly is active, highlight the first icon after user types a key on keyboard to filter.

This way, the user will always be sure that if he can see an item highlighted, pressing Enter will run it.
It seems consistent to me.

**Comment by PMunch** [comment] 2017-11-30 19:17
Another problem is how to define start. The current events for window focus and such are fired multiple times as the window is added the the window manager. What we could do is only use mouse move events, which would "solve" that part of the problem.

**Comment by Tomas-M** [comment] 2017-11-30 22:32
Currently, item under cursor is highlighted on start by the handling of EnterNotify event. This was added by this commit fd073ec5743969d77d30c657ca302acf4b12bc94 and there can be simple check (eg the event gets ignored unless there is some commandline parameter to highlight on start).

**Comment by Tomas-M** [comment] 2018-11-21 22:00
This ticket was originally opened for some other reason.
Nevertheless, it seems the original problem is not a bug. And my other issue (item highlighted under cursor when xlunch starts) was solved by a little hack here https://github.com/Tomas-M/xlunch/commit/35b0f849590fbb587e987bf0b5a1e49120b6fe57 (basically we wait few moves before we start highlighting). So I am clocing the ticket.

**Closed as completed by Tomas-M** 2018-11-21 22:00 UTC
